### ISSUE TITLE
Does not work with Xcode 9.3 / Swift 4.1

### ISSUE THREAD

**Issue by mbuchetics** [JohnSundell/Marathon#162]
The current version 2.0.2 does not run after installing Xcode 9.3:

```
~/Development > marathon --version

dyld: Symbol not found: __T0Sis11_StrideablesWP
  Referenced from: /usr/local/bin/marathon
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/marathon
[1]    5304 abort      marathon --version

~/Development > swift --version

Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
Target: x86_64-apple-darwin17.5.0
```

Changing the command line tools back to Xcode 9.2 (Swift 4.0.3) does not help, the above error is the same.

**Comment by JohnSundell** [comment]
It's being fixed here: https://github.com/JohnSundell/Marathon/pull/161 🙂

**Comment by mbuchetics** [comment]
That was quick, thank you 👍
